language: java
git:
  depth: false # Disable shallow fetch for sonarqube
jdk: openjdk11

script: ./gradlew check sonarqube -i -Dsonar.projectKey=vierbergenlars_plugin-updates-gradle-plugin -Dsonar.organization=vierbergenlars-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN

deploy:
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_SECURE_ENV_VARS"
  provider: script
  script: ./gradlew publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
